# 📝 Jobs Data Cleaning Notebook

## Project Overview
This notebook is focused on **cleaning and preparing jobs data**.  
We will perform the following tasks:

- Load data from a JSON file
- Explore and inspect the dataset
- Handle missing and inconsistent values
- Correct data types where necessary
- Save the cleaned data back to a JSON file

**Dataset:** Jobs information including job title, company, location, description

## 1️⃣ Imports

We start by importing the necessary libraries for data cleaning:

- **pandas**: For data manipulation and analysis  
- **json**: For reading and writing JSON files

In [1]:
import pandas as pd
import json

## 2️⃣ Load Data

We will load the raw jobs data from a JSON file into a Python object.  

- Using Python's built-in `json` library, we open the file in read mode (`"r"`) with UTF-8 encoding.  
- The `json.load()` function reads the JSON data and converts it into a Python dictionary or list, depending on the structure.

In [2]:
with open("../data/raw/raw_jobs.json", "r", encoding="utf-8") as f:
    jobs = json.load(f)

## 3️⃣ Convert to DataFrame

To make data analysis and cleaning easier, we convert the loaded jobs data into a **Pandas DataFrame**.  

- `pd.DataFrame()` takes the Python list/dictionary and creates a tabular structure.

In [3]:
df = pd.DataFrame(jobs)

## 4️⃣ Inspect Data

Before cleaning, it's important to **understand the structure and quality** of the dataset.  

- **Preview the data**  
  - `df.head()` – Shows the first 5 rows of the DataFrame  
  - `df.tail()` – Shows the last 5 rows  

- **Check data info**  
  - `df.info()` – Displays column names, data types, and non-null counts  

- **Check duplicates**  
  - `df.isna().sum()` – Counts the number of nulls

In [7]:
df.head()

,title,company,location,date_posted,skills_required,job_type,salary_min,salary_max,salary_avg,job_desc,link
0,Developer,CIBC India,"Hyderabad, Telangana",2026-01-20T08:35:48Z,"[Python, AI]",N/A,None,None,None,What Youll Be Doing (position summary): As a F...,https://www.adzuna.in/land/ad/5591948786?se=bq...
1,Developer,Birlasoft,"Hyderabad, Telangana",2026-02-17T09:43:06Z,"[Python, AWS, AI]",N/A,None,None,None,Job Description (Developer) Generative AI Deve...,https://www.adzuna.in/land/ad/5632728089?se=bq...
2,Developer,CIBC India,"Hyderabad, Telangana",2026-02-18T09:39:25Z,[AI],N/A,None,None,None,What Youll Be Doing (position summary): Design...,https://www.adzuna.in/land/ad/5634049986?se=bq...
3,Developer,Terra Technology Circle Consulting Private Lim...,"Delhi, India",2026-02-21T02:58:09Z,[AI],N/A,None,None,None,The profile open is for the role of a develope...,https://www.adzuna.in/land/ad/5638899970?se=bq...
4,Brand Development & Channel Development Manager,Lubz Corporation,"Mumbai, Maharashtra",2026-02-17T09:37:06Z,[Git],N/A,None,None,None,Industry: Automobile Department: Sales & Marke...,https://www.adzuna.in/land/ad/5632720468?se=bq...

In [8]:
df.tail()

,title,company,location,date_posted,skills_required,job_type,salary_min,salary_max,salary_avg,job_desc,link
995,Power Platform Developer,Insight Global,"Hyderabad, Telangana",2026-02-13T19:41:46Z,[],N/A,None,None,None,Job Description Evergreen is looking for a str...,https://www.adzuna.in/land/ad/5627767914?se=Yk...
996,Lead Product Developer,Agile Technology Solutions - Your Technology P...,India,2026-01-27T01:23:21Z,[],permanent,None,None,None,We’re Hiring | Product Lead – Java (Hybrid | ...,https://www.adzuna.in/land/ad/5601191570?se=Yk...
997,Google APIGEE Developer,Tata Consultancy Services,India,2026-02-17T09:42:29Z,"[AWS, GCP, Kubernetes, AI, Git]",N/A,None,None,None,Greetings from TATA Consultancy Services We ar...,https://www.adzuna.in/land/ad/5632727101?se=Yk...
998,Java developer & Support,RiVi Consulting Group L.L.C,"Hyderabad, Telangana",2026-02-20T03:01:09Z,[AI],N/A,None,None,None,"Key responsibilities, Built and maintained Jav...",https://www.adzuna.in/land/ad/5636676888?se=Yk...
999,Openings for Windchill developer,ITC Infotech,"Pune, Maharashtra",2026-02-14T01:24:57Z,[JavaScript],N/A,None,None,None,Technical Skills: Good knowledge of Windchill ...,https://www.adzuna.in/land/ad/5628295203?se=Yk...

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1000 non-null   str
 1   company          1000 non-null   str
 2   location         1000 non-null   str
 3   date_posted      1000 non-null   str
 4   skills_required  1000 non-null   object
 5   job_type         1000 non-null   str
 6   salary_min       0 non-null      object
 7   salary_max       0 non-null      object
 8   salary_avg       0 non-null      object
 9   job_desc         1000 non-null   str
 10  link             1000 non-null   str
dtypes: object(4), str(7)
memory usage: 86.1+ KB

In [10]:
df.isna().sum()

title                 0
company               0
location              0
date_posted           0
skills_required       0
job_type              0
salary_min         1000
salary_max         1000
salary_avg         1000
job_desc              0
link                  0
dtype: int64

# CLEANING STARTS

In [12]:
#SINCE ALL SALARY COLUMNS ARE EMPTY DROP THEM
df = df.drop('salary_avg',axis=1)
df = df.drop('salary_min',axis=1)
df = df.drop('salary_max',axis=1)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1000 non-null   str
 1   company          1000 non-null   str
 2   location         1000 non-null   str
 3   date_posted      1000 non-null   str
 4   skills_required  1000 non-null   object
 5   job_type         1000 non-null   str
 6   job_desc         1000 non-null   str
 7   link             1000 non-null   str
dtypes: object(1), str(7)
memory usage: 62.6+ KB

In [14]:
#DATE POSTED TO DATETIME
# Convert date_posted to datetime
df['date_posted'] = pd.to_datetime(df['date_posted'], errors='coerce')

# Check result
df.info()
df['date_posted'].head()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1000 non-null   str
 1   company          1000 non-null   str
 2   location         1000 non-null   str
 3   date_posted      1000 non-null   datetime64[us, UTC]
 4   skills_required  1000 non-null   object
 5   job_type         1000 non-null   str
 6   job_desc         1000 non-null   str
 7   link             1000 non-null   str
dtypes: datetime64[us, UTC](1), object(1), str(6)
memory usage: 62.6+ KB

0   2026-01-20 08:35:48+00:00
1   2026-02-17 09:43:06+00:00
2   2026-02-18 09:39:25+00:00
3   2026-02-21 02:58:09+00:00
4   2026-02-17 09:37:06+00:00
Name: date_posted, dtype: datetime64[us, UTC]

In [15]:
#Job_type might contain N/A values
df['job_type'].value_counts()

job_type
N/A          936
contract      44
permanent     20
Name: count, dtype: int64

In [16]:
df.drop('job_type',axis=1,inplace=True)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1000 non-null   str
 1   company          1000 non-null   str
 2   location         1000 non-null   str
 3   date_posted      1000 non-null   datetime64[us, UTC]
 4   skills_required  1000 non-null   object
 5   job_desc         1000 non-null   str
 6   link             1000 non-null   str
dtypes: datetime64[us, UTC](1), object(1), str(5)
memory usage: 54.8+ KB

In [18]:
#Clean Skills Required 
print(type(df['skills_required'][0]))

<class 'list'>

In [20]:
# Clean and standardize skills_required

df['skills_required'] = df['skills_required'].apply(
    lambda skills: list(
        set(
            skill.strip().lower() 
            for skill in skills
        )
    )
)

# Check result
df['skills_required'].head()

0         [python, ai]
1    [aws, python, ai]
2                 [ai]
3                 [ai]
4                [git]
Name: skills_required, dtype: object

In [21]:
#location
df['location'].head(10)

0    Hyderabad, Telangana
1    Hyderabad, Telangana
2    Hyderabad, Telangana
3            Delhi, India
4     Mumbai, Maharashtra
5                   India
6    Hyderabad, Telangana
7       Pune, Maharashtra
8        Noida, Ghaziabad
9    Hyderabad, Telangana
Name: location, dtype: str

In [22]:
df['location'].nunique()

38

In [23]:
df['location'].value_counts().head(10)

location
Hyderabad, Telangana        267
Pune, Maharashtra           229
India                       177
Bangalore, Karnataka        122
Mumbai, Maharashtra          70
Chennai, Tamil Nadu          34
Noida, Ghaziabad             19
Delhi, India                 12
Ahmedabad, Gujarat           11
Navi Mumbai, Maharashtra     11
Name: count, dtype: int64

In [24]:
# Clean and standardize location column

df['location'] = df['location'].apply(
    lambda x: x.strip().title()
)

# Check result
df['location'].head(10)

0    Hyderabad, Telangana
1    Hyderabad, Telangana
2    Hyderabad, Telangana
3            Delhi, India
4     Mumbai, Maharashtra
5                   India
6    Hyderabad, Telangana
7       Pune, Maharashtra
8        Noida, Ghaziabad
9    Hyderabad, Telangana
Name: location, dtype: str

In [25]:
# Split location into city and state
def split_location(loc):
    parts = [p.strip() for p in loc.split(',')]
    if len(parts) == 1:
        # Only country provided
        return None, parts[0]
    else:
        # City + State
        return parts[0], parts[1]

df['city'], df['state'] = zip(*df['location'].apply(split_location))

# Check result
df[['location','city','state']].head(10)

               location       city        state
0  Hyderabad, Telangana  Hyderabad    Telangana
1  Hyderabad, Telangana  Hyderabad    Telangana
2  Hyderabad, Telangana  Hyderabad    Telangana
3          Delhi, India      Delhi        India
4   Mumbai, Maharashtra     Mumbai  Maharashtra
5                 India        NaN        India
6  Hyderabad, Telangana  Hyderabad    Telangana
7     Pune, Maharashtra       Pune  Maharashtra
8      Noida, Ghaziabad      Noida    Ghaziabad
9  Hyderabad, Telangana  Hyderabad    Telangana

In [26]:
import numpy as np

df['state'] = df['state'].replace('India', np.nan)

# Optional: check result
df[['location','city','state']].head(10)

               location       city        state
0  Hyderabad, Telangana  Hyderabad    Telangana
1  Hyderabad, Telangana  Hyderabad    Telangana
2  Hyderabad, Telangana  Hyderabad    Telangana
3          Delhi, India      Delhi          NaN
4   Mumbai, Maharashtra     Mumbai  Maharashtra
5                 India        NaN          NaN
6  Hyderabad, Telangana  Hyderabad    Telangana
7     Pune, Maharashtra       Pune  Maharashtra
8      Noida, Ghaziabad      Noida    Ghaziabad
9  Hyderabad, Telangana  Hyderabad    Telangana

In [27]:
# Strip extra spaces from text columns
text_cols = ['title', 'company', 'job_desc']
for col in text_cols:
    df[col] = df[col].apply(lambda x: x.strip())

# Check result
df[['title','company','job_desc']].head(5)

,title,company,job_desc
0,Developer,CIBC India,What Youll Be Doing (position summary): As a F...
1,Developer,Birlasoft,Job Description (Developer) Generative AI Deve...
2,Developer,CIBC India,What Youll Be Doing (position summary): Design...
3,Developer,Terra Technology Circle Consulting Private Lim...,The profile open is for the role of a develope...
4,Brand Development & Channel Development Manager,Lubz Corporation,Industry: Automobile Department: Sales & Marke...

In [28]:
df = df.drop('location', axis=1)
df.head()

,title,company,date_posted,skills_required,job_desc,link,city,state
0,Developer,CIBC India,2026-01-20 08:35:48+00:00,"[python, ai]",What Youll Be Doing (position summary): As a F...,https://www.adzuna.in/land/ad/5591948786?se=bq...,Hyderabad,Telangana
1,Developer,Birlasoft,2026-02-17 09:43:06+00:00,"[aws, python, ai]",Job Description (Developer) Generative AI Deve...,https://www.adzuna.in/land/ad/5632728089?se=bq...,Hyderabad,Telangana
2,Developer,CIBC India,2026-02-18 09:39:25+00:00,[ai],What Youll Be Doing (position summary): Design...,https://www.adzuna.in/land/ad/5634049986?se=bq...,Hyderabad,Telangana
3,Developer,Terra Technology Circle Consulting Private Lim...,2026-02-21 02:58:09+00:00,[ai],The profile open is for the role of a develope...,https://www.adzuna.in/land/ad/5638899970?se=bq...,Delhi,NaN
4,Brand Development & Channel Development Manager,Lubz Corporation,2026-02-17 09:37:06+00:00,[git],Industry: Automobile Department: Sales & Marke...,https://www.adzuna.in/land/ad/5632720468?se=bq...,Mumbai,Maharashtra

# END OF NOTEBOOK SCRIPT IS IN ANALYSIS/cleaner.py (other steps depend on data provided)